apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeb-exc
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celeb-exc
  template:
    metadata:
      labels:
        app: celeb-exc
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: celeb-exc
          image: {{image-variable}}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: celeb-exc-svc
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: celeb-exc
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: celeb-exc-ingress
  namespace: production
  labels:
    app: celeb-exc-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{host-variable}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: celeb-exc-svc
            port:
              number: 80